### ISSUE TITLE
New acknowledgement page

### ISSUE THREAD

**Issue by kevinrae** [kevinrae/mosskey#17]
Create new acknowledgement page for Malcolm (& others).  

Need content

Put link in footer.
Update footer code.

**Comment by kevinrae** [comment]
Can you add the new page content here... or link to where I can get it? @stephenprae

**Comment by stephenprae** [comment]
Request out to Mac and Diane about their wishes.

**Comment by kevinrae** [comment]
This issue was moved to kevinrae/mosskey-www#10
