### ISSUE TITLE
Icons definition

### ISSUE THREAD

**Issue by stephenprae** [kevinrae/mosskey#25]
Three icons (eye, lens and scope) are great.  While we have declaration of them in the How To section, do you think we need something across the bottom of the Moss Key screen also?

**Comment by kevinrae** [comment]
Could be helpful... maybe... but consider that none of those icons are visible on the index page until you start clicking thru the dropdowns.   And... if you hover over any of the icons you get a tooltip that tells you what it is.

**Comment by kevinrae** [comment]
This issue was moved to kevinrae/mosskey-www#8
